all:
  # Define SSH user and private key
 vars:
   postgres_password: "pwd"
   postgres_user: "usr"
   postgres_db: "db"
   postgres_url: "database"
   ansible_user: centos # Set the SSH user to 'centos'

  # Define production hosts
 children:
   prod:
     hosts: elea.machillot.takima.cloud # The hostname of the production server
