- name: backend 
  docker_container:  
    name: backend  # Name of the Docker container 
    image: eleamct/tp-devops-simple-api:latest  # Docker image to use for the container
    pull: yes  # Pull the latest version 
    recreate: yes  # Recreate the container if it already exists
    networks:  # Define the networks 
      - name: app-network  
    env:  # Define environment variables for the container
      PASSWORD: "{{ postgres_password }}"  
      USERNAME: "{{ postgres_user }}" 
      DB: "{{ postgres_db }}"  
