name: CI devops 2023 - Build and Push ansible
on:
  push:
    branches:
      - main
      - develop

jobs:
  build-and-push-ansible:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Push ansible
        run: ansible-playbook -i /home/elea.machillot/Téléchargements/DevOps/ansible/inventories/setup.yml playbook.yml 