name: CI devops 2023 - Build and Push Docker Image

on:
  workflow_run:
    workflows: ["CI devops 2023 - Test Backend"]
    types:
      - completed

jobs:
  dummy-job:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy Step
        run: echo "This is a dummy step"

  build-and-push-docker-image:
    needs: dummy-job
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      # Add steps to build and push Docker images here
