name: CI devops 2023 - Build and Push ansible
on:
  workflow_run:
    workflows: ["CI devops 2023 - Build and Push Docker Image"]
    types:
      - completed

jobs:
  build-and-push-ansible:
    runs-on: ubuntu-22.04
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Install Python and Ansible dependencies
        run: sudo pip3 install ansible
      
      - name: Run Ansible playbook
        run: ansible-playbook -i ./ansible/inventories/setup.yml ./ansible/playbook.yml
