name: CI devops 2023 - Build and Push Docker Image
on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    needs: test-backend
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.5.0

      - name: Login to DockerHub
        run: docker login -u ${{ secrets.HUBUSERNAME }} -p ${{ secrets.HUBPASSWORD }}

      - name: Build and push backend image
        uses: docker/build-push-action@v3
        with:
          context: ./Back/simpleapi/simple-api-student-main
          tags: ${{ secrets.HUBUSERNAME }}/tp-devops-simple-api:latest
          push: true

      # Add steps to build and push other Docker images (database, httpd) here
